// Auto-generated by: pnpm sync:plans
// Do not edit manually — re-run the script after changing Stripe products.

export const plans = {
  basic: { name: "Basic", priceId: "price_1TQzZhG7Gvayjjm601pJ8OrY" },
  pro: { name: "Pro", priceId: "price_1TSj32G7Gvayjjm6l8dReLjM" },
  business: { name: "Business", priceId: "price_1TSkgMG7Gvayjjm6uRAvYoWh" },
} as const satisfies Record<string, { name: string; priceId: string }>;

export const oneTimeProducts = {
  book: { name: "Book", priceId: "price_1TQxtiG7Gvayjjm69gIee7a2" },
} as const satisfies Record<string, { name: string; priceId: string }>;

export type PlanKey = keyof typeof plans;
export type ProductKey = keyof typeof oneTimeProducts;
