// Auto-generated by: pnpm sm → sync-plans
// Do not edit manually — re-run the script after changing Polar products.
//
// Polar product naming convention:
// - Subscription plans: "{Plan} — Monthly" and "{Plan} — Yearly"
//   Grouped by base name (e.g. "starter" matches both monthly and yearly)
// - One-time products: just the product name (e.g. "Lifetime Deal" → "lifetimeDeal")

export const plans = {
  starter: {
    name: "Starter",
    monthlyProductId: "6c6afb05-cbc5-4a9a-adf5-ff103b653e14",
    yearlyProductId: "13607049-47e9-4231-b887-6043b8a40ad7",
  },
  pro: {
    name: "Pro",
    monthlyProductId: "aac5feb4-e2f3-4d25-969e-3003d966d90a",
    yearlyProductId: "e7f08198-58b7-4878-8627-351cef9ad5b8",
  },
  business: {
    name: "Business",
    monthlyProductId: "41657bb1-29f7-402e-9601-244801650b12",
    yearlyProductId: "fa6ce99e-9006-4033-8842-ad5adf296f4a",
  },
} as const satisfies Record<
  string,
  { name: string; monthlyProductId: string; yearlyProductId: string }
>;

export const oneTimeProducts = {
  starterKit: {
    name: "Starter Kit",
    productId: "150304b7-f404-4bd7-a9cd-a966f855067d",
  },
  lifetimeDeal: {
    name: "Lifetime Deal",
    productId: "e7e2c213-cce5-4c38-a06b-85f398d06937",
  },
} as const satisfies Record<string, { name: string; productId: string }>;

export type PlanKey = keyof typeof plans;
export type ProductKey = keyof typeof oneTimeProducts;
