// Auto-generated by: pnpm sm → sync-plans
// Do not edit manually — re-run the script after changing Polar products.
//
// Polar product naming convention:
// - Subscription plans: "{Plan} — Monthly" and "{Plan} — Yearly"
//   Grouped by base name (e.g. "starter" matches both monthly and yearly)
// - One-time products: just the product name (e.g. "Lifetime Deal" → "lifetimeDeal")

export const plans = {
  starter: {
    name: "Starter",
    monthlyProductId: "6fb02d2d-31d7-4561-ac41-208a10f22108",
    yearlyProductId: "48d66e73-44e9-4311-aef2-5bcb51fad0e1",
  },
  pro: {
    name: "Pro",
    monthlyProductId: "c9fc2cd0-bb42-4537-aea2-988b50ede19f",
    yearlyProductId: "e582ca11-f357-4a0d-a6da-870ae128b463",
  },
  enterprise: {
    name: "Enterprise",
    monthlyProductId: "5af387bc-4de2-400b-a115-0de99f7846ec",
    yearlyProductId: "11c4850c-ae5d-4408-9b7c-49e081b5c677",
  },
} as const satisfies Record<
  string,
  { name: string; monthlyProductId: string; yearlyProductId: string }
>;

export const oneTimeProducts = {} as const satisfies Record<
  string,
  { name: string; productId: string }
>;

export type PlanKey = keyof typeof plans;
export type ProductKey = keyof typeof oneTimeProducts;
