/**
 * Sync Plans — fetches all active Polar products and generates config/plans.ts
 * Run: pnpm sync:plans
 */

import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { Polar } from "@polar-sh/sdk";
import { config } from "dotenv";

const ROOT = resolve(import.meta.dirname, "..");

// ─── Check feature flag ────────────────────────────────────────────
const projectConfig: Record<string, unknown> = JSON.parse(
  readFileSync(resolve(ROOT, "config/config.json"), "utf-8")
);

if (!projectConfig.payments) {
  console.log(
    `\n  \x1b[43m\x1b[1m\x1b[37m ⚠ SKIPPED \x1b[0m  \x1b[33mpayments\x1b[0m is disabled in \x1b[33mconfig/config.json\x1b[0m\n`
  );
  process.exit(0);
}

config({ path: resolve(ROOT, ".env") });

// ─── Validate env ──────────────────────────────────────────────────
if (!process.env.POLAR_ACCESS_TOKEN?.trim()) {
  console.log(
    `\n  \x1b[41m\x1b[1m\x1b[37m ✗ MISSING \x1b[0m  \x1b[31mPOLAR_ACCESS_TOKEN\x1b[0m is not set in \x1b[33m.env\x1b[0m\n`
  );
  process.exit(1);
}

const polar = new Polar({
  accessToken: process.env.POLAR_ACCESS_TOKEN,
  server:
    (process.env.POLAR_SERVER as "sandbox" | "production") || "production",
});

// ─── ANSI helpers ──────────────────────────────────────────────────
const c = {
  reset: "\x1b[0m",
  bold: "\x1b[1m",
  dim: "\x1b[2m",
  green: "\x1b[32m",
  yellow: "\x1b[33m",
  cyan: "\x1b[36m",
  gray: "\x1b[90m",
  bgGreen: "\x1b[42m",
  bgRed: "\x1b[41m",
  white: "\x1b[37m",
  red: "\x1b[31m",
};

// ─── Helpers ───────────────────────────────────────────────────────
function toCamelCase(str: string): string {
  return str
    .replace(/[^a-zA-Z0-9\s]/g, "")
    .trim()
    .split(/\s+/)
    .map((word, i) =>
      i === 0
        ? word.toLowerCase()
        : word.charAt(0).toUpperCase() + word.slice(1).toLowerCase()
    )
    .join("");
}

function getPriceAmount(
  price: { amountType: string; priceAmount?: number } | undefined
): number {
  if (!price) return 0;
  return "priceAmount" in price ? (price.priceAmount ?? 0) : 0;
}

type PlanEntry = { key: string; name: string; productId: string };

// ─── Main ──────────────────────────────────────────────────────────
async function main() {
  console.log();

  let products: Awaited<
    ReturnType<typeof polar.products.list>
  >["result"]["items"];
  try {
    const result = await polar.products.list({});
    products = result.result.items.filter((p) => !p.isArchived);
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    console.log(
      `  ${c.bgRed}${c.bold}${c.white} ✗ POLAR API ${c.reset}  ${c.red}${msg}${c.reset}\n`
    );
    process.exit(1);
  }

  if (products.length === 0) {
    console.log(`  ${c.yellow}No active products found in Polar.${c.reset}\n`);
    process.exit(0);
  }

  const plans: PlanEntry[] = [];
  const oneTimeProducts: PlanEntry[] = [];

  for (const product of products) {
    const entry: PlanEntry = {
      key: toCamelCase(product.name),
      name: product.name,
      productId: product.id,
    };

    if (product.recurringInterval) {
      plans.push(entry);
    } else {
      oneTimeProducts.push(entry);
    }
  }

  // Sort by price (cheapest first)
  const sortByPrice = (a: PlanEntry, b: PlanEntry) => {
    const productA = products.find((p) => p.id === a.productId);
    const productB = products.find((p) => p.id === b.productId);
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    return (
      getPriceAmount(productA?.prices[0] as any) -
      getPriceAmount(productB?.prices[0] as any)
    );
  };

  plans.sort(sortByPrice);
  oneTimeProducts.sort(sortByPrice);

  // ─── Generate file ──────────────────────────────────────────────
  const formatEntries = (entries: PlanEntry[]) =>
    entries
      .map(
        (e) => `  ${e.key}: { name: "${e.name}", productId: "${e.productId}" },`
      )
      .join("\n");

  const content = `// Auto-generated by: pnpm sync:plans
// Do not edit manually — re-run the script after changing Polar products.

export const plans = {
${formatEntries(plans)}
} as const satisfies Record<string, { name: string; productId: string }>;

export const oneTimeProducts = {
${formatEntries(oneTimeProducts)}
} as const satisfies Record<string, { name: string; productId: string }>;

export type PlanKey = keyof typeof plans;
export type ProductKey = keyof typeof oneTimeProducts;
`;

  const outPath = resolve(ROOT, "config/plans.ts");
  writeFileSync(outPath, content, "utf-8");

  // ─── Output ─────────────────────────────────────────────────────
  console.log(
    `  ${c.bgGreen}${c.bold}${c.white} ✓ SYNCED ${c.reset}  ${c.green}config/plans.ts${c.reset}\n`
  );

  if (plans.length > 0) {
    console.log(`  ${c.bold}${c.cyan}Subscription Plans${c.reset}`);
    for (const p of plans) {
      console.log(
        `  ${c.green}│${c.reset} ${p.key} → ${c.dim}${p.name}${c.reset} ${c.gray}(${p.productId})${c.reset}`
      );
    }
    console.log();
  }

  if (oneTimeProducts.length > 0) {
    console.log(`  ${c.bold}${c.cyan}One-Time Products${c.reset}`);
    for (const p of oneTimeProducts) {
      console.log(
        `  ${c.green}│${c.reset} ${p.key} → ${c.dim}${p.name}${c.reset} ${c.gray}(${p.productId})${c.reset}`
      );
    }
    console.log();
  }

  console.log(
    `  ${c.gray}Update ${c.yellow}config/access.ts${c.gray} to map features to these plans.${c.reset}\n`
  );
}

main();
